id: applications_migration
label: applications migration from fermacrm
migration_group: default

source:
  plugin: 'csv'
  path: './applications.csv'
  delimiter: ','
  enclosure: '"'
  header_offset: 0
  ids:
    - id_requests
  fields:
    0:
      name: code
      label: 'code'
    1:
      name: id_requests
      label: 'id_requests'
    2:
      name: operation
      label: 'operation'
    3:
      name: price
      label: 'price'
    4:
      name: currency
      label: 'currency'
    5:
      name: min_rooms
      label: 'min_rooms'
    6:
      name: min_floor
      label: 'min_floor'
    7:
      name: max_floor
      label: 'max_floor'
    8:
      name: district_of_city
      label: 'district_of_city'
    9:
      name: motivation
      label: 'motivation'
    10:
      name: realtor
      label: 'realtor'
    11:
      name: type_of_person
      label: 'type_of_person'
    12:
      name: realeted_to
      label: 'realeted_to'
    13:
      name: subtype_of_realty
      label: 'type_of_realty'
    14:
      name: type_of_realty
      label: 'subtype_of_realty'
    15:
      name: field_appartment_plan
      label: 'field_appartment_plan'
    16:
      name: num_rooms
      label: 'num_rooms'
    17:
      name: field_min_area
      label: 'field_min_area'
    18:
      name: field_max_area
      label: 'field_max_area'
    19:
      name: application_status
      label: 'application_status'
    20:
      name: object_status
      label: 'object_status'
    21:
      name: description
      label: 'description'
    22:
      name: create
      label: 'create'
    23:
      name: change
      label: 'change'
    24:
      name: f24
    25:
      name: f25
    26:
      name: f26
    27:
      name: f27

    28:
      name: f28
    29:
      name: f29

    30:
      name: subdistrict_of_city
      label: 'subdistrict_of_city'
    31:
      name: last_date_contact
      label: 'last_date_contact'
    32:
      name: heating_system
      label: 'heating_system'

process:
  id: code

  field_operaciya_new:
    plugin: static_map
    bypass: true
    source: operation
    map:
      C0697800F264BD87A6FC66318F7F6EF4: 663
      6EBC4CAB2844A00953073A57FBE66019: 662

  field_price: price

  field_currency:
    plugin: static_map
    bypass: true
    source: currency
    map:
      # Євро
      3CB1CFE877A049D05E915B7AF26F5E1B: 636
      # Долари
      66423F3E7FC9CC4A64B5CEC3C90A7CE9: 635
      # Гривні
      839A039D0BA0D4C487AEAC7F461EA5F6: 634



  field_min_rooms: min_rooms

  field_min_floor: min_floor

  field_max_floor: max_floor

  field_district_of_the_city:
    plugin: static_map
    bypass: true
    source: district_of_city
    map:
      # Ковель
      5CA789AB4036788287D0CBA66003B571: 670
      # Ковельський р-н
      080895390E96E062EA63A4F8D4B79E7C: 671

  field_motivation_status:
    plugin: static_map
    bypass: true
    source: motivation
    map:
      BAD91720466411CFEB402A566F7AFA14: nevmotivovaniy
      5A713A20899BB18FD4D283811F867492: motivovaniy
      48D6668FEA07B09AD84770DAA3854A30: nedozriliy
      269340BD9D9C3DA4BBBE5874653AF7B0: gostra_motivaciya
      09E3CC9049E6C2AB32388B429600E6E3: ne_viznacheno

  field_realtor:
    plugin: static_map
    bypass: true
    source: realtor
    map:
      6C74C2E98300F2EC7964CE368A18E16C: 6645
      BDA99269836409DE658208CFC4939786: 6646
      E15FEFF8FC470C8C6C2F355DF7C94D96: 6647
      86F367D6AFEDCB4668CC8CE6D91F589C: 6648


  field_type_of_person:
    plugin: static_map
    bypass: true
    source: type_of_person
    map:
      A8F0B524CFF4D097B6C5539F404EE5DB: fizichna_osoba


  field_related_to:
    plugin: migration_lookup
    migration: users_migration
    source: realeted_to


  field_subtype_of_real_estate:
    plugin: static_map
    bypass: true
    source: subtype_of_realty
    map:
      # Дім
      A60505BF985E062B898BFBF321D655F2: 686
      # Дача
      BD6AD8125F2AA4E14C5F89D458511E0F: 688
      # Частина дому
      98A85583DCA56EB7D8FD76FB665E8751: 687
      # Комерційна земля
      A37BB67383F5A7EB8B6A39CB134DC3F6: 689
      # СГ
      A65F0CB584E7E36DB26D03D5F2633401: 690
      # Земля під застройку
      B9E6CE5558A4AA6D977EBA890407E691: 691
      # Земельна ділянка
      072C75AD521B28E537F7859A2862DD4B: 692
      # Квартира
      0EB03DFCCB6A86D9AE93DBB5219BC551: 693
      # Кімната
      85E6695A3615265E51CE17685601CF99: 694
      # Багатоцільова
      4E479096517622945D68AE4FF4B325DF: 695
      # СТО
      49936F6673F2B57F9D3CC7FDA12D9198: 696
      # Готельно-ресторанний комплекс
      758C5E1B126ED8A7C28EE3040DA5D6D5: 697
      # Офіс
      B459F7D23464F645E3792044810C41DD: 698
      # Торгова площадка
      55BC931CAA9A7CC3EC5A6B5A9D346119: 699

  field_type_of_real_estate:
    plugin: static_map
    bypass: true
    source: type_of_realty
    map:
      # Земельна ділянка
      DAC235A5E4245E03BDFEB1FF3A9EA6F9: 638
      # Квартири
      00830B915168D539E64CFC3AF04251BB: 639
      # Комерційна нерухомість
      3B11DFB0A39056ED92D064A0DA388D12: 640
      # Приватний сектор
      1FA205DE8037CA1D53E7004600301B81: 637


  field_appartment_plan:
    plugin: static_map
    bypass: true
    source: field_appartment_plan
    map:
      # Новобудова
      BF63C5FC56C821634640CDF0F0514C11: 664
      # Чешка
      CAF3799D2A1847FCB78FC903432A9AA7: 665
      # Покращене планування
      53C57306ECD5321C96D550FD8B0EC8E9: 666
      # Хрущівка
      B9A6268EA5C2142B6A51A5BA26A3252D: 667
      # Малосімейка
      F68BC999137E2D6FE83A3C47870E2047: 668
      # Кімната в гуртожитку
      D520741BD877635F3CD1C5BAF6F2C339: 669

  field_max_rooms: num_rooms

  field_min_area: field_min_area

  field_max_area: field_max_area

  field_state_of_application:
    plugin: static_map
    bypass: true
    source: application_status
    map:
      6BB448E41000182B0136B33575971BA7: dont_begin
      3881543C2346FB35FE996C9A7A717034: first_meeting
      1B3938AEC8A16BC43AA0F4FD576ECF5C: showing
      F9B3FF46F3539F542FAE396D0A9DF35B: given_offer
      9A632592A7177E716FA60E387CE9D5F5: offer_accepted
      78BD12EAF910BC6071365C25DC825058: given_part_of_money_in_advance
      8E7E28A52B02FBB308D17BE4B90F8E5A: deal_finished
      8106BAB3CD01886B665AA45A84D59B82: pause
      8F6C087CAD5E135F2523C344EC385175: deal_canceled
      0BC1EBF8A1AED8A5517DCCE480D36C58: buyed_without_us

  field_state_of_the_object:
    plugin: static_map
    bypass: true
    source: object_status
    map:
      E7B2EBD4224DBC5C935E1615703A026C: novobudova
      F8EFE987201E424804721C650B02063C: ievroremont
      B7F5C34D015DD9BD1A1BE54BF21DADB2: suchasniy_standart
      073BF3CD598F2956BB37B9A12D631D20: zhitloviy_stan
      FDDAAC762BA7116DA3834DE20C1FDB86: bez_remontu
      67CF10959F0AEEE05CC703BE1AF2C1B6: pidgotovleno_pid_remont
      777072E8177B0E7D517190F21C1B9466: potriben_kapitalniy_remont

  field_description: description

  created:
    plugin: callback
    callable: strtotime
    source: change_date

  changed: change

  field_subdistrict_of_city:
    plugin: static_map
    bypass: true
    source: subdistrict_of_city
    map:
      # Бреська
      9E5C7F51120ADBE316ED20BCB433219A: 672
      # Ковель-2
      F2D49E127A32081358BCB53529913586: 673
      # Ватутіна
      755BE48958584E447F9C2C9F6FD4ECED: 674
      # Сільмаш
      51A9BDA7E5875DAD419CA6DF3AE96629: 675
      # Володимирська
      C7EE51E9D3C2FDD3B77144318FCBA0A1: 676
      # Черемушкі
      146C2894F7BEB7B5F7C8A02FD1803529: 677
      # Привокзальна
      F75FC20C1622D89993D45BC8D7167F6B: 678
      # Центр
      3691EC359F2D7AEEF647E2FFF7356344: 679
      # Василька
      BB91423AB9A7CEB19F711E19C670D772: 680
      # Луків
      0190372EE6486936A250C55193E6A1EF: 681
      # Городилець
      03BC58E4274369932198C0C26BD98223: 682
      # Люблинець
      60E2764DABB483D3239BEA9655BEF265: 683
      # Голоби
      B29E4C6A8D8E2BA3C881F8C2C60D4EA3: 684
      # Турійськ
      08BF6DAD46F9580CDF55B64773F3E873: 685



  field_last_date_contact:
    plugin: format_date
    from_format: 'Y-m-d H:i:s'
    to_format: 'Y-m-d\TH:i:s'
    source: last_date_contact

  field_heating:
    plugin: static_map
    bypass: true
    source: heating_system
    map:
      # Газове
      71D333DE7BF010356834AC4913624C6F: 660
      # Електричне
      7E6F380F3BE8E7394FF6353AFEA1388B: 661


destination:
  plugin: entity:budova_applications
